name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx electron-packager "." "Project L.U.M.E.N." --ignore=data/ -–asar --overwrite --icon="img/icon.png" --out="build/"
      
      - name: Zip built versions
        run: |
          cd build
          for dir in */; do
            if [ "$RUNNER_OS" = "Windows" ]; then
              ( cd "$dir" && 7z a -tzip ../"${dir%/}".zip . )
            else
              ( cd "$dir" && zip -r ../"${dir%/}".zip . )
            fi
          done
        shell: bash

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*.zip
